version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env.backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file: .env.frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend